# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Elsa(object):
    def setupUi(self, Elsa):
        Elsa.setObjectName("Elsa")
        Elsa.resize(1366, 770)
        Elsa.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(Elsa)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(490, 220, 351, 351))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/DELL/Pictures/Saved Pictures/8871.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 200, 251, 401))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:/Users/DELL/Pictures/Saved Pictures/f889323d87ae92dbd5da3b1193708dc3.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(940, 10, 441, 271))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("C:/Users/DELL/Pictures/Saved Pictures/oFTHu7E.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, -50, 411, 241))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:/Users/DELL/Pictures/Saved Pictures/279b2e_194dd051fb5741e5b557654410e04d22_mv2.gif"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(480, 10, 401, 141))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("C:/Users/DELL/Pictures/Saved Pictures/932fd00d9b43753061c47739f0cc777b.gif"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1010, 320, 281, 251))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("C:/Users/DELL/Pictures/Saved Pictures/5da311e193e3d828e956ed010f95891b.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(490, 600, 361, 141))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("C:/Users/DELL/Pictures/Saved Pictures/1d735ad8eee8350adc96d50e1421ee6d.gif"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1020, 640, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1160, 640, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Eras Bold ITC")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(170, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        Elsa.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Elsa)
        self.statusbar.setObjectName("statusbar")
        Elsa.setStatusBar(self.statusbar)

        self.retranslateUi(Elsa)
        QtCore.QMetaObject.connectSlotsByName(Elsa)

    def retranslateUi(self, Elsa):
        _translate = QtCore.QCoreApplication.translate
        Elsa.setWindowTitle(_translate("Elsa", "MainWindow"))
        self.pushButton.setText(_translate("Elsa", "Run"))
        self.pushButton_2.setText(_translate("Elsa", "Terminate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Elsa = QtWidgets.QMainWindow()
    ui = Ui_Elsa()
    ui.setupUi(Elsa)
    Elsa.show()
    sys.exit(app.exec_())
